### PR TITLE
Fix/incorrect navigation bar on tab size view

### LINKED ISSUE #196: Monument detail view is broken on Desktop with mobile layout
https://github.com/user-attachments/assets/62c5972f-e4cc-4828-8044-c97b3d61ee87

### PR DESCRIPTION
**Pull request by HelloSniperMonkey**
#Description

This PR addresses the issue with the navigation bar and monument detail view when the app is used on Desktop and is resized to a screen size similar to a mobile display.

* fixed design size layout for web and big screens app like desktops.
* fixes random increase in layout size leading to overflow issues and some part of the viewable component being cut-off.
* Updated lib/main.dart to handle the changes in display size while resizing.
* Fixed the layout in monument_details_view_desktop.dart to ensure it renders properly on Desktop.
* Adjusted local_experts_card.dart to maintain a consistent display across different screen sizes and does not vanishes when there is less space.

This fixes the problem where the monument detail view was broken on Desktop and defaulting to a mobile layout, ensuring smooth functionality and proper UI behavior across all screen sizes.

Fixes: #196 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

by running it on multiple devices through device preview and checking if the problem persists 

Please include screenshots below if applicable.

https://github.com/user-attachments/assets/03b11cc1-1d71-4b23-9954-bc6f6c114a38

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

## Maintainer Checklist

- [x] closes #196

### CODE REVIEW

File: lib/main.dart [hunk 1]
```diff
@@ -52,7 +54,7 @@ class MyApp extends StatelessWidget {
     if (kIsWeb) {
       // if width is less than 530, it means the user resized the window to a smaller size
       if (MediaQuery.of(context).size.width < 530) {
-        designSize = const Size(390, 844);
+        designSize = const Size(1390, 844);
```
Comment (mdmohsin7) [inline lib/main.dart]: This design size is for mobile, it shouldn't be changed otherwise it will break on mobile

File: lib/presentation/popular_monuments/desktop/monument_details_view_desktop.dart [hunk 2]
```diff
@@ -406,7 +406,7 @@ class _MonumentDetailsViewDesktopState
                         borderRadius: BorderRadius.circular(12.sp),
                         image: DecorationImage(
                           image: CachedNetworkImageProvider(
-                            widget.monument.images[4],
+                            widget.monument.images[3],
```
Comment (mdmohsin7) [inline lib/presentation/popular_monuments/desktop/monument_details_view_desktop.dart]: I think there's a better solution than this, by default the app expects at least 6 images. The UI could be changed to have a carousel I guess? That way we wouldn't have to deal with the number of images being less than 6. The mobile UI implements a carousel for this, maybe you can just copy paste the implementation for desktop with some width/height changes

File: macos/Runner/AppDelegate.swift [hunk 3]
```diff
@@ -1,7 +1,7 @@
 import Cocoa
 import FlutterMacOS
 
-@NSApplicationMain
+@main
```
Comment (mdmohsin7) [inline macos/Runner/AppDelegate.swift:4]: Not sure why we have the native changes. Are they because of the latest version of flutter? If they were modified automatically then its fine

**Review by mdmohsin7 — CHANGES_REQUESTED** [review]

File: macos/Runner/AppDelegate.swift (hunk 3 above)
Comment (HelloSniperMonkey) [reply macos/Runner/AppDelegate.swift:4]: yes it was modified automatically when i used start debuging on macos

**Comment by HelloSniperMonkey** [comment]
https://github.com/user-attachments/assets/dc505cc6-b3d7-4da2-b640-5348e2c9c2c8

this video shows the problem faced with (390 ,844) design size 
and after changing it to (1390, 844) design size it seemed much better the fonts were not overly large and there were no overflow issue 
this was my observation on it so i went ahead and changed it

**Comment by HelloSniperMonkey** [comment]
sorry you were right it has some big issue when going inside contents 
will further look into fixing it

**Comment by HelloSniperMonkey** [comment]
Screenshot 2024-12-21 at 8 55 44 PM
with 1390, 844 
Screenshot 2024-12-21 at 8 56 23 PM
with 390, 844

**Comment by HelloSniperMonkey** [comment]
this fixes all the above mentioned issues 

https://github.com/user-attachments/assets/6b95c18d-f12a-492e-b434-de64f99781f7

**Review by mdmohsin7 — APPROVED** [review]
lgtm
